---

# Let us have a GUI player
#
- name: Rhythmbox
  apt:
    name: rhythmbox
  become: true
  tags:
    - player

# And then let us have some CLI players
#
- name: Mplayer
  apt:
    name: 
      - mplayer
      - cmus
  become: true
  tags:
    - radio
    - player

# Finally let us register a station
#
- name: Some radio-stations
  lineinfile:
    dest: ~/.bash_aliases
    mode: "0664"
    create: true
    regexp: "^alias {{ item.cmd }}="
    line: "alias {{ item.cmd }}='mplayer {{ item.url }}'"
  loop: "{{ radios }}"
  tags:
    - radio

