---

# Let us have a GUI player
#
- name: Rhythmbox
  apt:
    name: rhythmbox
  become: true
  tags:
    - player

# And then let us have some CLI players and tools
#
- name: Mplayer, cmus and beets
  apt:
    name: 
      - mplayer
      - cmus
      - beets
  become: true
  tags:
    - radio
    - player
