---

# Let us have a GUI player
#
- name: Rhythmbox
  apt:
    name: rhythmbox
  become: true
  tags:
    - player

# And then let us have some CLI players
#
- name: Mplayer
  apt:
    name: 
      - mplayer
      - cmus
  become: true
  tags:
    - radio
    - player
