---

- name: ProDeck
  hosts: localhost
  connection: local

  vars:
    nvidia:
      install: true
      version: 525

    # Attention: if you do not perfectly know what you are doing, 
    # the steam-client poses massive security risks!
    # If remote access is enabled in steam, it allows
    # complete remote access and not just accessing
    # games. You have been warned!
    #
    # Proper default for a work-environment would
    # be false!
    #
    enable_steam: true

  roles:
    - deck
    - regolith
    - browser
    - vscode
    - thunderbird
    - office
    - media
    - emacs
    - role: ssh
      tags: ssh
    - neovim
    - role: fail2ban
      tags: fail2ban
    - role: obs
      tags: obs
    - communication
    - virtualbox
    - hashicorp
    - role: vmware-workstation
      tags: vmw
    - role: alacritty
      tags: term
    - role: nvidia
      tags: nvidia
    - role: ssg
      tags: ssg
    - role: system-stats
      tags: stats
    - role: remote
      tags: rem
    - borg
    - role: steam
      tags: steam
    - user
    - role: retro
      tags: retro

  pre_tasks:

    # This tasks registers a variable when no tag has
    # been given for the run. Any other tasks may then
    # use this variable in a when-clause.
    #
    # Major benefit is to specify tasks that run
    # exclusively when no_tags is not defined and 
    # a given tag is. So the task would have:
    # 
    # tags:
    #   - mytag
    # when: no_tags is not defined
    #
    # A tasks equipped with an alike sequence will only
    # run when the tag is specified.
    #
    - name: no tags given
      debug:
        msg: registering no_tags variable
      register: no_tags

    # Any file with a .custom ending will be included
    # from the current directory. Files with such
    # suffix will be ignored by git.
    #
    # Later I will change this to use a specific directory.
    #
    - name: custom settings
      ansible.builtin.include_vars:
        dir: .
        ignore_unknown_extensions: true
        hash_behaviour: merge
        extensions:
          - 'custom'
      tags:
        - deck


    # Pretty much to be expected, is it not?
    #
    - name: update apt cache and upgrade apt packages
      apt:
        update_cache: true
        upgrade: full
      become: true
      tags:
        - apt

  tasks:

    - name: add some python
      apt:
        name:
          - python3-venv
      become: true
      tags:
        - python

    # In some future this is going to be chucked into a role.
    #
    - name: Install a selection of snap-apps
      snap:
        name:
          - openscad
      become: true      
      tags:
        - snaps
      
