---

- name: ProDeck
  hosts: all

  roles:
    - regolith
    - googlechrome
    - vscode
    - thunderbird
    - office
    - media
    - obs
    - communication
    - virtualbox
    - hashicorp
    - role: vmware-workstation
      tags: vmw

  tasks:

    - name: mc, screen, vim
      apt:
        name: 
          - mc
          - screen
          - vim
      become: true

    - name: adding alias to bashrc
      lineinfile:
        path: ~/.bash_aliases
        regex: "alias play="
        line: "alias play=ansible-playbook"
        create: yes
      

      
      
