---

- name: ProDeck
  hosts: localhost
  connection: local

  vars:
    nvidia:
      install: false
      version: 525

  roles:
    - regolith
    - googlechrome
    - vscode
    - thunderbird
    - office
    - media
    - role: obs
      tags: obs
    - communication
    - virtualbox
    - hashicorp
    - role: vmware-workstation
      tags: vmw
    - role: alacritty
      tags: term
    - role: nvidia
    - music
    - role: ssg
      tags: ssg
    - role: system-stats
      tags: stats
    - role: remote
      tags: rem
    - borg

  tasks:

    - name: mc, screen, vim
      apt:
        name: 
          - mc
          - screen
          - vim
      become: true

    - name: some tools -> 7z, nmap, net-tools (netstat)
      apt:
        name:
          - p7zip
          - nmap
          - net-tools
      become: true
      tags: tools

    - name: add some python
      apt:
        name:
          - python3-venv
      become: true
      tags:
        - python

    - name: adding alias to bashrc
      lineinfile:
        path: ~/.bash_aliases
        regex: "alias play="
        line: "alias play=ansible-playbook"
        create: yes
      
    - name: Install a selection of snap-apps
      snap:
        name:
          - openscad
      become: true      
      tags:
        - snaps
      
