---

- name: ProDeck
  hosts: localhost
  connection: local

  vars:
    nvidia:
      install: true
      version: 525

    # Attention: if you do not perfectly know what you are doing, 
    # the steam-client poses massive security risks!
    # If remote access is enabled in steam, it allows
    # complete remote access and not just accessing
    # games. You have been warned!
    #
    # Proper default for a work-environment would
    # be false!
    #
    enable_steam: true

  roles:
    - regolith
    - googlechrome
    - vscode
    - thunderbird
    - office
    - media
    - emacs
    - role: ssh
      tags: ssh
    - neovim
    - role: fail2ban
      tags: fail2ban
    - role: obs
      tags: obs
    - communication
    - virtualbox
    - hashicorp
    - role: vmware-workstation
      tags: vmw
    - role: alacritty
      tags: term
    - role: nvidia
    - role: ssg
      tags: ssg
    - role: system-stats
      tags: stats
    - role: remote
      tags: rem
    - borg
    - role: steam
      tags: steam
    - user
    - role: retro
      tags: retro

  tasks:

    - name: add some python
      apt:
        name:
          - python3-venv
      become: true
      tags:
        - python

    - name: Install a selection of snap-apps
      snap:
        name:
          - openscad
      become: true      
      tags:
        - snaps
      
