---

- name: "Steam is {{ deck.uses.steam | ternary('enabled', 'disabled') }}"
  snap:
    name: steam
    state: "{{ deck.uses.steam | ternary('present', 'absent') }}"
  become: true

- name: "Note!"
  debug:
    msg: "Steam is a security risk!"
  when: deck.uses.steam
