---

- name: Install ffmpeg
  apt:
    name:
      - ffmpeg
    state: latest
  become: true

- name: How do we install OBS?
  debug:
    msg: "{{ obs_from_snap | ternary('as snap','via apt')}}"

- name: "Assure the OBS repository is {{ obs_from_snap | ternary('absent','present')}}"
  ansible.builtin.apt_repository:
    filename: obs-repo
    repo: "ppa:obsproject/obs-studio"
    state: "{{ obs_from_snap | ternary('absent','present')}}"
  become: true

- name: "Assure the OBS package is {{ obs_from_snap | ternary('absent','latest')}}"
  apt:
    name:
      - obs-studio
    state: "{{ obs_from_snap | ternary('absent','latest')}}"
  become: true

- name: "Assure the OBS Studio snap to be {{ obs_from_snap | ternary('present','absent')}}"
  snap:
    name:
      - obs-studio
    state: "{{ obs_from_snap | ternary('present','absent')}}"
  become: true

- name: "screenkey"
  apt:
    name: screenkey
    state: latest
  become: true
