---

- name: "Manage Nvidia Drivers ({{ deck.nvidia.install | ternary('enabled','disabled') }})"
  apt:
    name:
      - "nvidia-driver-{{ deck.nvidia.version }}"
      - "nvidia-dkms-{{ deck.nvidia.version }}"
    state:  "{{ deck.nvidia.install | ternary('latest', 'absent') }}"
  become: true
  tags: nvidia
