---

- name: "Install Nvidia Drivers ({{ nvidia.install | ternary('enabled','disabled') }})"
  apt:
    name:
      - "nvidia-driver-{{ nvidia.version }}"
      - "nvidia-dkms-{{ nvidia.version }}"
    state:  "{{ nvidia.install | ternary('present', 'absent') }}"
  become: true
  tags: nvidia
