---

- name: Install regolith repository key
  ansible.builtin.get_url:
    url: "https://regolith-desktop.org/regolith.key"
    dest: /usr/share/keyrings/regolith-archive-keyring.asc
    mode: "0644"
    force: true
  become: true

- name: Add the repo for regolith
  ansible.builtin.apt_repository:
    filename: regolith-repo
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.asc] https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main"
    state: present
  become: true

- name: Install regolith-desktop
  apt:
    name:
    - regolith-desktop
    - regolith-compositor-picom-glx
  become: true

- name: Install any possibly required fonts
  apt:
    name:
      - fonts-jetbrains-mono
      - fonts-source-code-pro-ttf
      - fonts-nerd-font-hack
      - fonts-nerd-font-ibmplexmono
  become: true
  tags:
    - xregs
    - fonts

- name: Install flameshot (maybe later integrated in regolith)
  apt:
    name:
      flameshot
  become: true
  tags: flameshot

- name: Assure the local i3 config partials directory
  file:
    path: ~/.config/regolith2/i3/config.d
    state: directory
    mode: "0755"
  tags: flameshot

# A copy would likely do it, but I expect configurables to end up here.
- name: Deploy some keybindings for i3
  template:
    src: "{{ item }}"
    dest: ~/.config/regolith2/i3/config.d
    mode: "0644"
  loop:
    - flameshot-keys.i3
    - workspace-kicker.i3
  tags: keys

- name: Copy the Xresources
  template:
    src: Xresources
    dest: ~/.Xresources
    mode: "0644"
  notify: refresh regolith-look
  tags:
    - xres

- name: Create the directory for the backgrounds
  file:
    path: ~/.Xbackgrounds
    state: directory
    mode: "0755"
  notify: refresh regolith-look

- name: Copy a number of background files
  copy:
    src: "{{ item }}"  
    dest: ~/.Xbackgrounds
    mode: "0644"
  loop:
    - sunset-1.png
    - sunset-2.png
    - sunset-3.png
    - sunset-4.png
  notify: refresh regolith-look

