---

# This is all about working with the shell.


- name: My basics
  apt:
    name:
      - vim
      - screen
  become: true

- name: Utilities ... ranger, htop, tmux, ncdu, thef*ck
  apt:
    name: 
      - ranger
      - htop
      - tmux
      - ncdu
  become: true

# Proposed by Tech Craft on youtube: https://www.youtube.com/watch?v=2OHrTQVlRMg
#
- name: Utilities ... mc, exa, fzf, ripgrep, zoxide, bat, entr
  apt:
    name: 
      - mc
      - exa
      - fzf
      - ripgrep
      - zoxide
      - bat
      - entr
  become: true

# Proposed by dev.to: https://dev.to/lissy93/cli-tools-you-cant-live-without-57f6
# 
- name: Utilities ...
  apt:
    name:
      - thefuck
      - duf
      - aria2
      - fdupes
      - jq
      - most
  become: true

- name: Some cosmetic toys
  apt:
    name:
      - cmatrix
      - hollywood
      - neofetch
      - cpufetch
  become: true

- name: some tools -> 7z, nmap, net-tools (netstat)
  apt:
    name:
      - p7zip
      - nmap
      - net-tools
  become: true
  tags: tools

- name: Internet speedtest
  apt:
    name:
      - speedtest-cli
  become: true
  tags: internet

- name: lazygit - as a snap (forgive me ;-), I'm lazy after all)
  snap:
    name: lazygit-gm
    classic: true
  become: true
  tags: lg

