- name: Handly the alacritty repository
  ansible.builtin.apt_repository:
    filename: alacritty-repo
    repo: "ppa:aslatter/ppa"
  become: true

- name: Install Alacritty
  apt:
    name:
      - alacritty
  become: true

- name: Configuration directory for Alacritty
  file:
    path: ~/.config/alacritty
    state: directory
    mode: '0755'

# https://github.com/eendroroy/alacritty-theme
# 
# There are examples on the website
#
- name: Download alacritty-themes
  git:
    repo: https://github.com/eendroroy/alacritty-theme.git
    dest: ~/.config/alacritty-colorscheme
  tags: scheme

- name: Alacritty's configuration
  template:
    src: alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml
    mode: '0644'
    
