- name: Handly the alacritty repository
  ansible.builtin.apt_repository:
    filename: alacritty-repo
    repo: "ppa:aslatter/ppa"
  become: true
  when: deck.uses.alacritty

- name: Install Alacritty
  apt:
    name:
      - alacritty
  become: true
  when: deck.uses.alacritty and deck.is.pc

- name: Install alacritty (snap)
  snap:
    name:
      - alacritty
    classic: true
  become: true
  when: deck.uses.alacritty and deck.is.rpi

- name: Configuration directory for Alacritty
  file:
    path: ~/.config/alacritty
    state: directory
    mode: '0755'
  when: deck.uses.alacritty

# https://github.com/eendroroy/alacritty-theme
# 
# There are examples on the website
#
- name: Download alacritty-themes
  git:
    repo: https://github.com/eendroroy/alacritty-theme.git
    dest: ~/.config/alacritty-colorscheme
  tags: scheme
  when: deck.uses.alacritty

- name: Alacritty's configuration
  template:
    src: alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml
    mode: '0644'
  when: deck.uses.alacritty
    
